name: Update Version

on:
  schedule:
    - cron: '0 * * * *'
    
  workflow_dispatch:
permissions:
  contents: write

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run update version script
      run: |
        chmod +x update.sh
        ./update.sh
        git push
        
