name: Update Version

on:
  schedule:
    - cron: '0 */12 * * *'
    
  workflow_dispatch:
permissions:
  contents: write

jobs:
  version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run update version script
      run: |
        chmod +x update.sh
        ./update.sh
        git push
        
  update:
    needs: version
    runs-on: ubuntu-latest

    container:
      image: fedora:41
      options: --volume ${{ github.workspace }}:/workspace

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install dependencies
        run: |
          dnf install -y git rpm-build createrepo_c curl jq tar

      - name: Prepare and Build RPM
        run: |
          git clone https://${{ secrets.PAT }}@github.com/burhancodes/materialgram-repo.git repo
          chmod +x build.sh
          ./build.sh
